# Generated by Django 2.1.15 on 2021-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
