# Generated by Django 2.1.15 on 2021-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_article_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '友联管理',
                'verbose_name_plural': '友联管理',
                'db_table': 'tb_links',
            },
        ),
    ]
